version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '3000:3000'
    external_links:
      - mongo
    volumes:
      - ./:/usr/src/app
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: